### ISSUE TITLE
linear-progress-indicator should have initial value

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-wc-examples#300]
progress bar should be initialized to a value of 50-75 

https://staging.infragistics.com/webcomponents-demos/samples/inputs/linear-progress-indicator-dynamic

**Comment by MonikaKirkova** [comment]
Since our goal is to ensure that the demos in both Angular and Web components have a consistent appearance, if we make changes to the Web components sample, those changes should be reflected in the other products' samples.
I will discuss this change with our UX and Design team, but we would appreciate it if you could provide us with additional details about why this change is preferable.

**Comment by MonikaKirkova** [comment]
@sdimchevski, @simeonoff what do you think, should we set value for the linear progress indicator in the WC sample as well as in Angular and Blazor?

**Comment by simeonoff** [comment]
I agree with @HUSSAR-mtrela. Perhaps a non-zero default value will be a better example as a starting point. @sdimchevski what do you think? @MonikaKirkova I agree that we should update the Angular samples as well if this change is made.

**Comment by sdimchevski** [comment]
I agree. It's generally better to show a non-zero default value (such as 50-75) to demonstrate the visual appearance and functionality of the progress bar and to provide a clear understanding of what the progress bar looks like.
