### ISSUE TITLE
Remove componentRenderer from grid and tree-grid samples

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-wc-examples#369]
![image](https://user-images.githubusercontent.com/44684385/214318485-0a79a3e3-ebfe-4de1-abe3-0487426033af.png)

**Comment by gmurray81** [comment]
that is required if something is using the editor panel. Using the editor panel is not often necessary, instead a sample should maybe be broken into a few simpler samples instead.

If a sample has the renderer and is NOT using the editor panel, this is usually caused by if in the json definition of the sample "withDescriptions" is included in the modules list. Just make sure to remove this from the modules list if the editor panel is not in use.

**Comment by damyanpetev** [comment]
CC @dkamburov

**Comment by dkamburov** [comment]
Looks like we have "withDescriptions" modules in a lot of our samples, that probably don't need it. I'll try review those and remove it where not needed.

**Comment by gmurray81** [comment]
@dkamburov just keep in mind if it's using the property editor panel this IS required.
